version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
      - echo "Entered into pre build"
      - bash ./gradlew clean
  build:
    commands:
      - echo "Entered into build"
      - bash ./gradlew build
  post_build:
    commands:
      - echo "Entered into post build"
      - mv build/libs/cicd-0.0.1-SNAPSHOT.war ROOT.war
artifacts:
  files:
    - ROOT.war
